### PR TITLE
Account for relative path anchor

### LINKED ISSUE #23: Figure path misspecified during knit process
Hi again, Yihui.

I've encountered a minor build error when creating new posts. In short, none of the figures render correctly when I try to add/knit new .Rmd files via `blogdown::build_site()`.

I believe the problem occurs because the `gsub` function on [line 12](https://github.com/yihui/blogdown-jekyll/blob/gh-pages/R/build_one.R#L12) of `build_one.R` doesn't account for the fact that the preceding shell script call (i.e. [here](https://github.com/yihui/blogdown-jekyll/blob/gh-pages/R/build.R#L6)) prepends `./` to create the relative path. The upshot is that this messes up the figure path that the resulting .md file is supposed to reference against. We end up adding an extra `./` and also fail to remove the leading underscore in `_posts`. 

(FWIW I don't think you would have encountered this issue, because you are specifying a special Dropbox path for your own figures.)

Here's a simple example where my .Rmd file is just printing `plot(1:10)`. 

If I build/serve the site with this new .Rmd file, the post appears but the image is missing. 

bdj1

It's clear what went wrong from the actual knitted .md file. Again, the figure path is misspecified because of the extra `./_` after "/figure".

```md
{% highlight r %}
plot(1:10)
{% endhighlight %}

![plot of chunk unnamed-chunk-1](/figure/./_posts/2020-10-16-test1/unnamed-chunk-1-1.png)
```

Ofc the pretty simple solution is just to account for this extra `./` in the original `gsub()` function. If I do that and rebuild/serve, then everything works as expected.

bdj2

I'll submit a PR with this little patch.

### PR DESCRIPTION
**Pull request by grantmcdermott**
Fixes #23

### CODE REVIEW

File: R/build_one.R [hunk 1]
```diff
@@ -9,7 +9,7 @@ local({
 
   # input/output filenames are passed as two additional arguments to Rscript
   a = commandArgs(TRUE)
-  d = gsub('^_|[.][a-zA-Z]+$', '', a[1])
+  d = gsub('^./_|[.][a-zA-Z]+$', '', a[1])
```
Comment (yihui) [inline R/build_one.R]: `.` is a special character (which matches any character), so you need to either escape it or put it in `[]`, e.g.

```suggestion
  d = gsub('^[.]/_|[.][a-zA-Z]+$', '', a[1])
```

**Review by yihui — CHANGES_REQUESTED** [review]
Thank you!

File: R/build_one.R (hunk 1 above)
Comment (grantmcdermott) [reply R/build_one.R]: Sorry, sloppy on my part. Done!

**Review by yihui — APPROVED** [review]
